/**
 * ComicCraft core domain types — shared by the story engines, the art engine,
 * the layout builder, the PDF exporter, API routes and the UI.
 */

export interface ComicInput {
  prompt: string;
  character: string;
  setting: string;
  tone: string;
  style: string;
}

/** Structured outline row produced by the outline stage (Gemini Flash / local). */
export interface PanelOutline {
  panel: number;
  title: string;
  /** Scene description — the italic atmosphere paragraph under each panel. */
  scene: string;
  /** Raw prompt handed to the image engine. */
  imagePrompt: string;
}

/** Story text produced by the narration stage (Gemini Pro / local). */
export interface PanelStory {
  /** Ambient caption — background sound / environment note. */
  caption: string;
  /** Comic narration for the panel. */
  narration: string;
  /** Character dialogue lines, rendered as speech bubbles. */
  dialogue: string[];
}

export type Beat = "arrival" | "journey" | "peril" | "climax" | "legacy";

/**
 * A full descriptor for the procedurally illustrated panel artwork.
 * Deterministic from (setting, tone, style, beat, seed) so the web preview and
 * the PDF exporter always render the exact same image.
 */
export interface SceneArt {
  beat: Beat;
  setting: string;
  tone: string;
  style: string;
  seed: number;
  /** Character archetype key used by the glyph painter. */
  hero: HeroKind;
  /** Optional path to a raster illustration generated by a diffusion backend. */
  png?: string;
}

export type HeroKind = "fox" | "robot" | "cat" | "owl" | "astronaut" | "dragon" | "hero";

/** Fully bound panel — the unit stored in the database and rendered everywhere. */
export interface ComicPanel {
  panel: number;
  title: string;
  scene: string;
  imagePrompt: string;
  caption: string;
  narration: string;
  dialogue: string[];
  art: SceneArt;
}

export interface Comic {
  id: string;
  title: string;
  prompt: string;
  character: string;
  setting: string;
  tone: string;
  style: string;
  engine: string;
  panels: ComicPanel[];
  createdAt: string;
}

export const TONES = ["dramatic", "funny", "poetic", "light-hearted"] as const;
export const STYLES = ["anime", "comic book", "pixel art", "realistic"] as const;
export const SETTINGS = ["forest", "city", "space", "school"] as const;

export const PANEL_COUNT = 5;
